services:
  - type: web
    name: season-tickets
    env: node
    buildCommand: npm install && node src/database/init.js && node src/database/seed.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
